---
- name: Get mtci disk usage
  hosts: vms_mtci03 
  become: yes

  tasks:
  - name: Running df -h 
    command: df -h
    register: output

#  - debug: msg="{{ output.stdout }}"
  - debug: var=output.stdout_lines
    
